# Generated by Django 4.1.7 on 2023-11-14 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myexpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expensename', models.CharField(max_length=50)),
                ('ProfitAmount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(max_length=500)),
                ('total_amount', models.FloatField(default=0.0)),
            ],
        ),
    ]
