# Generated by Django 4.1.7 on 2023-11-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myexpense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myexpense',
            name='total_amount',
        ),
    ]
